### ISSUE TITLE
<SafeAreaView /> usage

### ISSUE THREAD

**Issue by guilhermedeoliveira** [FotonTech/foton-chat#1] opened 2018-12-03 22:02 UTC
Have you, guys, tried instantiating `<SafeAreaView />` just once at the top level component?

```
<SafeAreaView style={{ flex: 1 }}>
  <App />
</SafeAreaView>
```

**Comment by socksrust** [comment] 2018-12-04 01:58
@guilhermedeoliveira PRs are welcome

**Comment by socksrust** [comment] 2018-12-04 01:58
u can use styled components for the {flex:1}!!

**Comment by socksrust** [comment] 2018-12-04 02:22
https://github.com/FotonTech/foton-chat/blob/master/app/src/App.tsx

**Comment by socksrust** [comment] 2018-12-04 02:54
The problem is, we need different SafeAreaView background colors for different screens.

**Comment by socksrust** [comment] 2018-12-04 02:54
![screen shot 2018-12-04 at 00 53 20](https://user-images.githubusercontent.com/13947203/49415857-19b44b00-f75f-11e8-9b7d-a312f10859ed.png)

**Comment by guilhermedeoliveira** [comment] 2018-12-04 15:51
hum... that's a problem. Unless you instantiate again `SafeAreaView`. But you are right.

**Comment by socksrust** [comment] 2018-12-04 20:52
i'll close the issue, thanks Gui!

**Closed as completed by socksrust** 2018-12-04 20:52 UTC
